### Create user
POST localhost:8083/registration
Content-Type: application/json

{"name": "Sally"}

### Get user
GET localhost:8083/users/4

### Get account
GET localhost:8083/accounts?ownerId=4

### Create project
POST localhost:8083/projects
Content-Type: application/json

{"name": "Basket Weaving III", "accountId": 2}

### Get projects
GET localhost:8083/projects?accountId=1

### Create allocation
POST localhost:8081/allocations
Content-Type: application/json

{"projectId": 11, "userId": 4, "firstDay": "2015-05-17", "lastDay": "2015-05-18"}

### Get allocations
GET localhost:8081/allocations?projectId=11

### Create story
POST {{backlogUrl}}/stories
Content-Type: application/json

{"projectId": PROJECT-ID, "name": "Find some reeds"}

### Get stories
GET {{backlogUrl}}/stories?projectId=PROJECT-ID

### Create timesheet
POST {{timesheetsUrl}}/time-entries/
Content-Type: application/json

{"projectId": PROJECT-ID, "userId": USER-ID, "date": "2015-05-17", "hours": 6}

### Get timesheets
GET {{timesheetsUrl}}/time-entries?userId=USER-ID

###
